name: Build Website

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/build_web.yml'

jobs:
  deploy:
    name: Deploy
    if: github.event_name == 'push'
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build site
        working-directory: ./web
        run: |
          npm install
          npm run build
        
      - name: Deploy Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.GCP_CREDENTIALS }}"
          projectId: meseta-lgtm
          channelId: live
